<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ChetnaM-PC" ignored="0" name="suite1" tests="2" failures="1" timestamp="09 Mar 2017 06:41:02 GMT" time="116.674" errors="0">
  <testcase name="verify" time="56.71" classname="com.adv.qa.selenium.tests.currency.A001_Switch_Intra_Company_Accounting_OnTest"/>
  <testcase name="verify" time="24.736" classname="com.adv.qa.selenium.tests.currency.A002_Currency_DescriptionTest">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.adv.qa.selenium.framework.pageObjects.currency.CurrencyPage.addNewCurrency(CurrencyPage.java:290)
	at com.adv.qa.selenium.tests.currency.A002_Currency_DescriptionTest.createCurrency(A002_Currency_DescriptionTest.java:95)
	at com.adv.qa.selenium.tests.currency.A002_Currency_DescriptionTest.verify(A002_Currency_DescriptionTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verify -->
</testsuite> <!-- suite1 -->
